import xlsxwriter
from .flurstueck import Flurstueck

class XLSXExporter:
    def __init__(self, path):
        self._workbook = xlsxwriter.Workbook(path)
        self._worksheet = self._workbook.add_worksheet()
        self._fs_counter = 0

        self._generic_format = self._workbook.add_format()
        self._generic_format.set_align("top")
        self._generic_format.set_align("left")
        self._generic_format.set_text_wrap()

        self._title_format = self._workbook.add_format()
        self._title_format.set_bold()

        self._worksheet.write_string(0, 0, "Flurstückskennzeichen (ALB 4 stl.)", self._title_format)
        self._worksheet.write_string(0, 1, "Flurstückskennzeichen (ALK 4 stl.)", self._title_format)
        self._worksheet.write_string(0, 2, "Flurstückskennzeichen (ALB 3 stl.)", self._title_format)
        self._worksheet.write_string(0, 3, "Flurstückskennzeichen (ALK 3 stl.)", self._title_format)
        self._worksheet.write_string(0, 4, "Flurstückskennzeichen (ALKIS)", self._title_format)
        self._worksheet.write_string(0, 5, "ALKIS_ObjektID", self._title_format)
        self._worksheet.write_string(0, 6, "Bundesland", self._title_format)
        self._worksheet.write_string(0, 7, "Regierungsbezirk", self._title_format)
        self._worksheet.write_string(0, 8, "Landkreis", self._title_format)
        self._worksheet.write_string(0, 9, "Gemeinde", self._title_format)
        self._worksheet.write_string(0, 10, "Gemarkung", self._title_format)
        self._worksheet.write_string(0, 11, "Flur", self._title_format)
        self._worksheet.write_string(0, 12, "Flurstücksnummer", self._title_format)
        self._worksheet.write_string(0, 13, "Katasteramt", self._title_format)
        self._worksheet.write_string(0, 14, "Finanzamt", self._title_format)
        self._worksheet.write_string(0, 15, "Forstamt", self._title_format)
        self._worksheet.write_string(0, 16, "amtliche Fläche m²", self._title_format)
        self._worksheet.write_string(0, 17, "Objektkoordinate X", self._title_format)
        self._worksheet.write_string(0, 18, "Objektkoordinate Y", self._title_format)
        self._worksheet.write_string(0, 19, "unverschl. Lagebezeichnung", self._title_format)
        self._worksheet.write_string(0, 20, "Straße Hausnummer", self._title_format)
        self._worksheet.write_string(0, 21, "Hinweis", self._title_format)
        self._worksheet.write_string(0, 22, "Entstehung", self._title_format)
        self._worksheet.write_string(0, 23, "Lebenszeitintervall beginnt", self._title_format)
        self._worksheet.write_string(0, 24, "Lebenszeitintervall endet", self._title_format)
        self._worksheet.write_string(0, 25, "Vorgängerflurstück", self._title_format)
        self._worksheet.write_string(0, 26, "Nachfolgerflurstück", self._title_format)
        self._worksheet.write_string(0, 27, "Nutzung", self._title_format)
        self._worksheet.write_string(0, 28, "Klassifizierung", self._title_format)
        self._worksheet.write_string(0, 29, "Bodenschätzung", self._title_format)
        self._worksheet.write_string(0, 30, "Bewertung", self._title_format)
        self._worksheet.write_string(0, 31, "Eigentum", self._title_format)

    def addFlurstueck(self, fs: Flurstueck):
        self._fs_counter = self._fs_counter + 1

        self._worksheet.write_string(self._fs_counter, 0, fs.kennzeichenALB4stl(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 1, fs.kennzeichenALK4stl(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 2, fs.kennzeichenALB3stl(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 3, fs.kennzeichenALK3stl(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 4, fs.kennzeichenALKIS(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 5, fs.gml_id(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 6, fs.bundesland(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 7, fs.regierungsbezirk(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 8, fs.kreisregion(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 9, fs.gemeinde(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 10, fs.gemarkung(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 11, fs.flurnummer(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 12, fs.flurstuecksnummer(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 13, fs.katasteramt(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 14, fs.finanzamt(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 15, fs.forstamt(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 16, fs.amtlicheflaeche(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 17, fs.koordinate_x(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 18, fs.koordinate_y(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 19, fs.unverschluesselte_lagebezeichnung(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 20, fs.strasse_hausnummer(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 21, fs.hinweis(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 22, fs.entstehung(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 23, fs.lebenszeitintervall_beginnt(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 24, fs.lebenszeitintervall_endet(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 25, fs.vorgaengerflurstueck(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 26, fs.nachfolgerflurstueck(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 27, fs.nutzung(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 28, fs.klassifizierung(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 29, fs.bodenschaetzung(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 30, fs.bewertung(), self._generic_format)
        self._worksheet.write_string(self._fs_counter, 31, fs.eigentum(), self._generic_format)

        pass

    def save(self):
        self._worksheet.autofit()
        self._workbook.close()
